import { useEffect, useMemo, useState } from 'react'
import { isSupabaseConfigured, supabase } from './lib/supabase.js'
import { demoProducts } from './demoData.js'
import ProductCard from './components/ProductCard.jsx'
import ProductVisual from './components/ProductVisual.jsx'
import OfferCard from './components/OfferCard.jsx'
import SetupNotice from './components/SetupNotice.jsx'
import PriceHistoryChart from './components/PriceHistoryChart.jsx'

const money=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'})
const categoryIcons={Smartphone:'📱',Telefonia:'📱',Informatica:'💻',Computer:'💻',TV:'📺',Gaming:'🎮',Moda:'👟',Scarpe:'👟',Sport:'⚽',Casa:'🏠',Elettrodomestici:'🏠',Audio:'🎧'}
function totalPrice(o){return Number(o.price||0)+Number(o.shipping_cost||0)}
function sortOffers(ps){return ps.map(p=>({...p,offers:[...(p.offers||[])].sort((a,b)=>totalPrice(a)-totalPrice(b))}))}
function convenienceScore(o,offers){const totals=offers.map(totalPrice),min=Math.min(...totals),max=Math.max(...totals),total=totalPrice(o),priceScore=max===min?10:10-((total-min)/(max-min))*3,s=o.stores||{},r=Math.min(Number(s.return_days||0)/30,1)*1.2,w=Math.min(Number(s.warranty_months||0)/24,1)*1.2,sh=Number(o.shipping_cost||0)===0?.6:0,a=/disponibile|pronta|immediata/i.test(o.availability||'')?.4:0;return Math.min(10,Math.round((priceScore*.66+r+w+sh+a)*10)/10)}
function productHistory(p){return(p.offers||[]).flatMap(o=>o.price_history||[]).map(x=>({...x,total_price:Number(x.total_price??(Number(x.price||0)+Number(x.shipping_cost||0)))})).sort((a,b)=>new Date(a.recorded_at)-new Date(b.recorded_at))}
function priceInsight(p){const h=productHistory(p).map(x=>x.total_price),current=p.offers?.[0]?totalPrice(p.offers[0]):null;if(!current||h.length<2)return null;const average=h.reduce((a,b)=>a+Number(b),0)/h.length,historicalMin=Math.min(...h),difference=((current-average)/average)*100;let label='Buon prezzo',tone='good',message='Il prezzo attuale è vicino alla media recente.';if(difference<=-8){label='Ottimo prezzo';tone='great';message='Il prezzo attuale è nettamente sotto la media recente.'}else if(difference>6){label='Aspetta';tone='wait';message='Il prezzo attuale è sopra la media recente.'}return{current,average,historicalMin,difference,label,tone,message}}
function SiteFooter(){return <footer><span>Comparing · Confronta meglio, scegli meglio</span><nav><a href="/affiliazioni.html">Affiliazioni</a><a href="/privacy.html">Privacy</a><a href="mailto:comparing.support@gmail.com">Contatti</a></nav></footer>}

export default function App(){
 const[products,setProducts]=useState(sortOffers(demoProducts)),[selectedProduct,setSelectedProduct]=useState(null),[query,setQuery]=useState(''),[category,setCategory]=useState('Tutte'),[loading,setLoading]=useState(isSupabaseConfigured),[error,setError]=useState(''),[favorites,setFavorites]=useState(()=>JSON.parse(localStorage.getItem('comparing-favorites')||'[]')),[showFavorites,setShowFavorites]=useState(false)
 async function loadProducts(){if(!isSupabaseConfigured||!supabase){setProducts(sortOffers(demoProducts));setLoading(false);return}setLoading(true);setError('');const{data,error:fetchError}=await supabase.from('products').select(`id,brand,name,category,description,image_url,offers(id,price,shipping_cost,availability,product_url,updated_at,price_history(price,shipping_cost,total_price,recorded_at),stores(id,name,website_url,return_days,warranty_months,shipping_notes))`).order('brand',{ascending:true});if(fetchError){setError(fetchError.message);setProducts(sortOffers(demoProducts))}else setProducts(sortOffers(data||[]));setLoading(false)}
 useEffect(()=>{loadProducts()},[])
 const categories=useMemo(()=>['Tutte',...new Set(products.map(p=>p.category).filter(Boolean))],[products])
 const filteredProducts=useMemo(()=>{const term=query.trim().toLowerCase();return products.filter(p=>(!showFavorites||favorites.includes(p.id))&&(category==='Tutte'||p.category===category)&&(!term||`${p.brand} ${p.name} ${p.category}`.toLowerCase().includes(term)))},[products,query,category,showFavorites,favorites])
 function toggleFavorite(id){setFavorites(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id];localStorage.setItem('comparing-favorites',JSON.stringify(next));return next})}
 async function trackClick(id){if(!supabase||String(id).startsWith('demo-'))return;const{error:e}=await supabase.from('clicks').insert({offer_id:id});if(e)console.warn(e.message)}
 function openStore(o){window.open(o.product_url,'_blank','noopener,noreferrer');trackClick(o.id)}
 if(selectedProduct){const offers=selectedProduct.offers||[],history=productHistory(selectedProduct),scored=offers.map(offer=>({offer,score:convenienceScore(offer,offers)})),recommendedId=[...scored].sort((a,b)=>b.score-a.score)[0]?.offer?.id,insight=priceInsight(selectedProduct),cheapest=offers[0]?totalPrice(offers[0]):0;return <div className="app-shell"><header className="topbar"><button className="brand-button" onClick={()=>setSelectedProduct(null)}><span className="brand-mark">C</span> Comparing</button><nav className="topnav"><button onClick={()=>setSelectedProduct(null)}>Categorie</button><button onClick={()=>setSelectedProduct(null)}>Offerte</button><button onClick={()=>{setSelectedProduct(null);setShowFavorites(true)}}>♡ Preferiti</button></nav><span className="demo-pill">BETA</span></header><main className="container"><button className="back-button" onClick={()=>setSelectedProduct(null)}>← Torna ai prodotti</button><section className="product-hero"><ProductVisual product={selectedProduct}/><div><span className="category-chip">{selectedProduct.category}</span><h1>{selectedProduct.brand} {selectedProduct.name}</h1><p>{selectedProduct.description||'Confronta le offerte disponibili.'}</p><button className="alert-button">🔔 Avvisami quando il prezzo scende</button></div></section>{insight&&<section className={`price-insight ${insight.tone}`}><div><span className="insight-label">PREZZO OGGI</span><strong>{insight.label}</strong><p>{insight.message}</p></div><div className="price-stats"><div><span>Attuale</span><b>{money.format(insight.current)}</b></div><div><span>Media recente</span><b>{money.format(insight.average)}</b></div><div><span>Minimo storico</span><b>{money.format(insight.historicalMin)}</b></div></div></section>}{history.length>0&&<PriceHistoryChart history={history} currentPrice={cheapest}/>}<section><div className="section-heading"><div><p className="eyebrow">CONFRONTA DAVVERO</p><h2>Prezzo più basso e miglior acquisto</h2></div><span>{offers.length} offerte</span></div><div className="offers-list">{offers.map((o,i)=><OfferCard key={o.id} offer={o} isCheapest={i===0} isRecommended={o.id===recommendedId} score={convenienceScore(o,offers)} cheapestTotal={cheapest} onOpenStore={openStore}/>)}</div></section></main><SiteFooter/></div>}
 const featured=filteredProducts.slice(0,3)
 return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">C</span> Comparing</div><nav className="topnav"><button onClick={()=>{setCategory('Tutte');setShowFavorites(false)}}>Categorie</button><button onClick={()=>document.querySelector('#offerte')?.scrollIntoView({behavior:'smooth'})}>Offerte</button><button onClick={()=>setShowFavorites(v=>!v)}>♡ Preferiti {favorites.length?`(${favorites.length})`:''}</button></nav><span className="demo-pill">BETA</span></header><main className="container">
 <section className="intro"><p className="eyebrow">IL MOTORE DI RICERCA PER I TUOI ACQUISTI</p><h1>Trova il prezzo migliore.<br/><span>Scegli l'acquisto giusto.</span></h1><p>Confrontiamo prezzo totale, spedizione, reso e garanzia. Tu scegli con più informazioni e meno dubbi.</p><div className="hero-search"><span>⌕</span><input type="search" placeholder="Cerca iPhone, PS5, Nike Air Max…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>document.querySelector('#offerte')?.scrollIntoView({behavior:'smooth'})}>Confronta</button></div><div className="trust-row"><span>✓ Prezzi trasparenti</span><span>✓ Nessun ranking a pagamento</span><span>✓ Convenienza spiegata</span></div></section>
 {!isSupabaseConfigured&&<SetupNotice/>}{error&&<section className="error-state"><strong>Supabase non ha risposto correttamente.</strong><span>{error}</span><button onClick={loadProducts}>Riprova</button></section>}
 <section className="category-section"><div className="section-heading"><div><p className="eyebrow">ESPLORA</p><h2>Cosa stai cercando?</h2></div></div><div className="category-strip">{categories.filter(x=>x!=='Tutte').map(c=><button key={c} className={category===c?'active':''} onClick={()=>{setCategory(c);setShowFavorites(false)}}><span>{categoryIcons[c]||'🛍️'}</span><strong>{c}</strong></button>)}</div></section>
 <section className="highlights"><div className="highlight-card green"><span>⭐</span><div><small>IL NOSTRO METODO</small><h3>Non vince sempre chi costa meno.</h3><p>Comparing considera anche spedizione, reso e garanzia per indicarti il miglior acquisto.</p></div></div><div className="highlight-card"><span>📉</span><div><small>STORICO PREZZI</small><h3>Capisci se è il momento giusto.</h3><p>Media recente e minimo storico ti aiutano a distinguere un vero affare.</p></div></div></section>
 <section id="offerte"><div className="section-heading"><div><p className="eyebrow">{showFavorites?'I TUOI PREFERITI':'SCELTI PER TE'}</p><h2>{showFavorites?'Prodotti salvati':'Offerte e confronti'}</h2></div><select value={category} onChange={e=>{setCategory(e.target.value);setShowFavorites(false)}}>{categories.map(c=><option key={c}>{c}</option>)}</select></div>{loading&&<div className="empty-state">Caricamento prodotti…</div>}{!loading&&!filteredProducts.length&&<div className="empty-state">{showFavorites?'Non hai ancora salvato prodotti. Tocca ♡ su una card.':'Nessun prodotto trovato.'}</div>}{!loading&&<div className="product-grid">{(featured.length?filteredProducts:[]).map(p=><ProductCard key={p.id} product={p} onCompare={setSelectedProduct} isFavorite={favorites.includes(p.id)} onToggleFavorite={toggleFavorite}/>)}</div>}</section>
 <section className="ad-slot"><span>SPAZIO PUBBLICITARIO</span><p>Qui potranno comparire contenuti sponsorizzati chiaramente indicati. Non influenzeranno mai il ranking Comparing.</p></section>
 </main><SiteFooter/></div>
}
