export const demoProducts = [
  {
    id: 'demo-sony',
    brand: 'Sony',
    name: 'WH-CH520',
    category: 'Elettronica',
    description: 'Cuffie wireless leggere con autonomia elevata.',
    image_url: '',
    price_history: [49.99, 47.99, 45.99, 44.99, 42.99, 39.99],
    offers: [
      {
        id: 'demo-offer-sony-1',
        price: 39.99,
        shipping_cost: 0,
        availability: 'Disponibile',
        product_url: 'https://www.mediaworld.it',
        updated_at: new Date().toISOString(),
        stores: { id: 'demo-store-1', name: 'MediaWorld', return_days: 14, warranty_months: 24, shipping_notes: '2-4 giorni' },
      },
      {
        id: 'demo-offer-sony-2',
        price: 42.99,
        shipping_cost: 4.99,
        availability: 'Disponibile',
        product_url: 'https://www.unieuro.it',
        updated_at: new Date().toISOString(),
        stores: { id: 'demo-store-2', name: 'Unieuro', return_days: 14, warranty_months: 24, shipping_notes: '3-5 giorni' },
      },
    ],
  },
  {
    id: 'demo-nike',
    brand: 'Nike',
    name: 'Sneaker Demo',
    category: 'Abbigliamento',
    description: 'Esempio per mostrare il confronto anche nel settore moda.',
    image_url: '',
    price_history: [74.99, 76.99, 72.99, 77.99, 75.99, 79.99],
    offers: [
      {
        id: 'demo-offer-nike-1',
        price: 79.99,
        shipping_cost: 0,
        availability: 'Disponibile',
        product_url: 'https://www.zalando.it',
        updated_at: new Date().toISOString(),
        stores: { id: 'demo-store-3', name: 'Zalando', return_days: 30, warranty_months: 24, shipping_notes: '2-5 giorni' },
      },
      {
        id: 'demo-offer-nike-2',
        price: 84.99,
        shipping_cost: 3.90,
        availability: 'Disponibile',
        product_url: 'https://www.ovs.it',
        updated_at: new Date().toISOString(),
        stores: { id: 'demo-store-4', name: 'OVS', return_days: 30, warranty_months: 24, shipping_notes: '3-6 giorni' },
      },
    ],
  },
]
