-- MIGRAZIONE PER INSTALLAZIONI ESISTENTI
-- Esegui questo file nel SQL Editor di Supabase se hai già eseguito 01_schema.sql in passato.

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  offer_id uuid not null references public.offers(id) on delete cascade,
  price numeric(10,2) not null check (price >= 0),
  shipping_cost numeric(10,2) not null default 0 check (shipping_cost >= 0),
  total_price numeric(10,2) generated always as (price + shipping_cost) stored,
  recorded_at timestamptz not null default now()
);

create index if not exists price_history_offer_id_idx on public.price_history(offer_id);
create index if not exists price_history_recorded_at_idx on public.price_history(recorded_at desc);
create index if not exists price_history_offer_recorded_idx on public.price_history(offer_id, recorded_at desc);

alter table public.price_history enable row level security;

drop policy if exists public_read_price_history on public.price_history;
create policy public_read_price_history
on public.price_history
for select
using (true);

-- Inserisce una prima rilevazione per le offerte già presenti.
-- NOT EXISTS rende questa operazione sicura anche se il file viene eseguito una seconda volta.
insert into public.price_history (offer_id, price, shipping_cost, recorded_at)
select o.id, o.price, o.shipping_cost, o.updated_at
from public.offers o
where not exists (
  select 1
  from public.price_history ph
  where ph.offer_id = o.id
);

-- Non viene creata alcuna policy INSERT pubblica.
-- I futuri aggiornamenti dello storico dovranno arrivare da un processo server/autorizzato.
